import { useState } from "react";
import { Input } from "@/components/ui/input";
import Icon from "@/components/ui/icon";

interface Word {
  word: string;
  translation: string;
  category: string;
}

const words: Word[] = [
  // Местоимения
  { word: "I", translation: "я", category: "Местоимения" },
  { word: "you", translation: "ты, вы", category: "Местоимения" },
  { word: "he", translation: "он", category: "Местоимения" },
  { word: "she", translation: "она", category: "Местоимения" },
  { word: "it", translation: "оно", category: "Местоимения" },
  { word: "we", translation: "мы", category: "Местоимения" },
  { word: "they", translation: "они", category: "Местоимения" },
  { word: "me", translation: "меня, мне", category: "Местоимения" },
  { word: "him", translation: "его, ему", category: "Местоимения" },
  { word: "her", translation: "её, ей", category: "Местоимения" },
  { word: "us", translation: "нас, нам", category: "Местоимения" },
  { word: "them", translation: "их, им", category: "Местоимения" },
  { word: "my", translation: "мой, моя", category: "Местоимения" },
  { word: "your", translation: "твой, ваш", category: "Местоимения" },
  { word: "his", translation: "его", category: "Местоимения" },
  { word: "our", translation: "наш", category: "Местоимения" },
  { word: "their", translation: "их", category: "Местоимения" },
  { word: "this", translation: "это (близко)", category: "Местоимения" },
  { word: "that", translation: "то (далеко)", category: "Местоимения" },
  { word: "these", translation: "эти", category: "Местоимения" },
  { word: "those", translation: "те", category: "Местоимения" },
  { word: "who", translation: "кто", category: "Местоимения" },
  { word: "what", translation: "что, какой", category: "Местоимения" },
  { word: "which", translation: "который", category: "Местоимения" },
  { word: "whose", translation: "чей", category: "Местоимения" },
  { word: "someone", translation: "кто-то", category: "Местоимения" },
  { word: "something", translation: "что-то", category: "Местоимения" },
  { word: "everyone", translation: "все", category: "Местоимения" },
  { word: "everything", translation: "всё", category: "Местоимения" },
  { word: "nobody", translation: "никто", category: "Местоимения" },
  // Существительные — Люди
  { word: "man", translation: "мужчина", category: "Люди" },
  { word: "woman", translation: "женщина", category: "Люди" },
  { word: "boy", translation: "мальчик", category: "Люди" },
  { word: "girl", translation: "девочка", category: "Люди" },
  { word: "child", translation: "ребёнок", category: "Люди" },
  { word: "baby", translation: "младенец", category: "Люди" },
  { word: "friend", translation: "друг", category: "Люди" },
  { word: "family", translation: "семья", category: "Люди" },
  { word: "mother", translation: "мать", category: "Люди" },
  { word: "father", translation: "отец", category: "Люди" },
  { word: "brother", translation: "брат", category: "Люди" },
  { word: "sister", translation: "сестра", category: "Люди" },
  { word: "son", translation: "сын", category: "Люди" },
  { word: "daughter", translation: "дочь", category: "Люди" },
  { word: "husband", translation: "муж", category: "Люди" },
  { word: "wife", translation: "жена", category: "Люди" },
  { word: "grandfather", translation: "дедушка", category: "Люди" },
  { word: "grandmother", translation: "бабушка", category: "Люди" },
  { word: "uncle", translation: "дядя", category: "Люди" },
  { word: "aunt", translation: "тётя", category: "Люди" },
  { word: "cousin", translation: "двоюродный брат/сестра", category: "Люди" },
  { word: "neighbor", translation: "сосед", category: "Люди" },
  { word: "teacher", translation: "учитель", category: "Люди" },
  { word: "student", translation: "студент", category: "Люди" },
  { word: "doctor", translation: "врач", category: "Люди" },
  { word: "nurse", translation: "медсестра", category: "Люди" },
  { word: "police", translation: "полиция", category: "Люди" },
  { word: "boss", translation: "начальник", category: "Люди" },
  { word: "worker", translation: "рабочий", category: "Люди" },
  { word: "driver", translation: "водитель", category: "Люди" },
  // Существительные — Дом
  { word: "house", translation: "дом", category: "Дом" },
  { word: "apartment", translation: "квартира", category: "Дом" },
  { word: "room", translation: "комната", category: "Дом" },
  { word: "kitchen", translation: "кухня", category: "Дом" },
  { word: "bedroom", translation: "спальня", category: "Дом" },
  { word: "bathroom", translation: "ванная", category: "Дом" },
  { word: "door", translation: "дверь", category: "Дом" },
  { word: "window", translation: "окно", category: "Дом" },
  { word: "floor", translation: "пол / этаж", category: "Дом" },
  { word: "wall", translation: "стена", category: "Дом" },
  { word: "roof", translation: "крыша", category: "Дом" },
  { word: "table", translation: "стол", category: "Дом" },
  { word: "chair", translation: "стул", category: "Дом" },
  { word: "bed", translation: "кровать", category: "Дом" },
  { word: "sofa", translation: "диван", category: "Дом" },
  { word: "lamp", translation: "лампа", category: "Дом" },
  { word: "mirror", translation: "зеркало", category: "Дом" },
  { word: "clock", translation: "часы", category: "Дом" },
  { word: "phone", translation: "телефон", category: "Дом" },
  { word: "computer", translation: "компьютер", category: "Дом" },
  { word: "television", translation: "телевизор", category: "Дом" },
  { word: "key", translation: "ключ", category: "Дом" },
  { word: "bag", translation: "сумка", category: "Дом" },
  { word: "box", translation: "коробка", category: "Дом" },
  { word: "bottle", translation: "бутылка", category: "Дом" },
  { word: "cup", translation: "чашка", category: "Дом" },
  { word: "glass", translation: "стакан / стекло", category: "Дом" },
  { word: "plate", translation: "тарелка", category: "Дом" },
  { word: "spoon", translation: "ложка", category: "Дом" },
  { word: "fork", translation: "вилка", category: "Дом" },
  // Еда и напитки
  { word: "food", translation: "еда", category: "Еда" },
  { word: "water", translation: "вода", category: "Еда" },
  { word: "milk", translation: "молоко", category: "Еда" },
  { word: "tea", translation: "чай", category: "Еда" },
  { word: "coffee", translation: "кофе", category: "Еда" },
  { word: "juice", translation: "сок", category: "Еда" },
  { word: "bread", translation: "хлеб", category: "Еда" },
  { word: "butter", translation: "масло", category: "Еда" },
  { word: "cheese", translation: "сыр", category: "Еда" },
  { word: "egg", translation: "яйцо", category: "Еда" },
  { word: "meat", translation: "мясо", category: "Еда" },
  { word: "chicken", translation: "курица", category: "Еда" },
  { word: "fish", translation: "рыба", category: "Еда" },
  { word: "rice", translation: "рис", category: "Еда" },
  { word: "soup", translation: "суп", category: "Еда" },
  { word: "salad", translation: "салат", category: "Еда" },
  { word: "apple", translation: "яблоко", category: "Еда" },
  { word: "banana", translation: "банан", category: "Еда" },
  { word: "orange", translation: "апельсин", category: "Еда" },
  { word: "lemon", translation: "лимон", category: "Еда" },
  { word: "tomato", translation: "помидор", category: "Еда" },
  { word: "potato", translation: "картошка", category: "Еда" },
  { word: "carrot", translation: "морковь", category: "Еда" },
  { word: "onion", translation: "лук", category: "Еда" },
  { word: "garlic", translation: "чеснок", category: "Еда" },
  { word: "salt", translation: "соль", category: "Еда" },
  { word: "sugar", translation: "сахар", category: "Еда" },
  { word: "cake", translation: "торт", category: "Еда" },
  { word: "chocolate", translation: "шоколад", category: "Еда" },
  { word: "ice cream", translation: "мороженое", category: "Еда" },
  // Одежда
  { word: "clothes", translation: "одежда", category: "Одежда" },
  { word: "shirt", translation: "рубашка", category: "Одежда" },
  { word: "pants", translation: "брюки", category: "Одежда" },
  { word: "dress", translation: "платье", category: "Одежда" },
  { word: "skirt", translation: "юбка", category: "Одежда" },
  { word: "jacket", translation: "куртка", category: "Одежда" },
  { word: "coat", translation: "пальто", category: "Одежда" },
  { word: "shoes", translation: "туфли, обувь", category: "Одежда" },
  { word: "boots", translation: "сапоги", category: "Одежда" },
  { word: "hat", translation: "шляпа", category: "Одежда" },
  { word: "scarf", translation: "шарф", category: "Одежда" },
  { word: "gloves", translation: "перчатки", category: "Одежда" },
  { word: "socks", translation: "носки", category: "Одежда" },
  { word: "sweater", translation: "свитер", category: "Одежда" },
  { word: "jeans", translation: "джинсы", category: "Одежда" },
  { word: "t-shirt", translation: "футболка", category: "Одежда" },
  { word: "underwear", translation: "нижнее бельё", category: "Одежда" },
  { word: "uniform", translation: "форма", category: "Одежда" },
  { word: "suit", translation: "костюм", category: "Одежда" },
  { word: "tie", translation: "галстук", category: "Одежда" },
  // Природа
  { word: "sun", translation: "солнце", category: "Природа" },
  { word: "moon", translation: "луна", category: "Природа" },
  { word: "star", translation: "звезда", category: "Природа" },
  { word: "sky", translation: "небо", category: "Природа" },
  { word: "cloud", translation: "облако", category: "Природа" },
  { word: "rain", translation: "дождь", category: "Природа" },
  { word: "snow", translation: "снег", category: "Природа" },
  { word: "wind", translation: "ветер", category: "Природа" },
  { word: "storm", translation: "буря", category: "Природа" },
  { word: "river", translation: "река", category: "Природа" },
  { word: "sea", translation: "море", category: "Природа" },
  { word: "ocean", translation: "океан", category: "Природа" },
  { word: "lake", translation: "озеро", category: "Природа" },
  { word: "mountain", translation: "гора", category: "Природа" },
  { word: "forest", translation: "лес", category: "Природа" },
  { word: "tree", translation: "дерево", category: "Природа" },
  { word: "flower", translation: "цветок", category: "Природа" },
  { word: "grass", translation: "трава", category: "Природа" },
  { word: "earth", translation: "земля", category: "Природа" },
  { word: "fire", translation: "огонь", category: "Природа" },
  { word: "ice", translation: "лёд", category: "Природа" },
  { word: "stone", translation: "камень", category: "Природа" },
  { word: "sand", translation: "песок", category: "Природа" },
  { word: "island", translation: "остров", category: "Природа" },
  { word: "desert", translation: "пустыня", category: "Природа" },
  // Животные
  { word: "dog", translation: "собака", category: "Животные" },
  { word: "cat", translation: "кошка", category: "Животные" },
  { word: "bird", translation: "птица", category: "Животные" },
  { word: "fish", translation: "рыба", category: "Животные" },
  { word: "horse", translation: "лошадь", category: "Животные" },
  { word: "cow", translation: "корова", category: "Животные" },
  { word: "pig", translation: "свинья", category: "Животные" },
  { word: "sheep", translation: "овца", category: "Животные" },
  { word: "chicken", translation: "курица", category: "Животные" },
  { word: "rabbit", translation: "кролик", category: "Животные" },
  { word: "mouse", translation: "мышь", category: "Животные" },
  { word: "lion", translation: "лев", category: "Животные" },
  { word: "tiger", translation: "тигр", category: "Животные" },
  { word: "bear", translation: "медведь", category: "Животные" },
  { word: "wolf", translation: "волк", category: "Животные" },
  { word: "fox", translation: "лиса", category: "Животные" },
  { word: "elephant", translation: "слон", category: "Животные" },
  { word: "monkey", translation: "обезьяна", category: "Животные" },
  { word: "snake", translation: "змея", category: "Животные" },
  { word: "frog", translation: "лягушка", category: "Животные" },
  // Транспорт
  { word: "car", translation: "машина", category: "Транспорт" },
  { word: "bus", translation: "автобус", category: "Транспорт" },
  { word: "train", translation: "поезд", category: "Транспорт" },
  { word: "plane", translation: "самолёт", category: "Транспорт" },
  { word: "ship", translation: "корабль", category: "Транспорт" },
  { word: "boat", translation: "лодка", category: "Транспорт" },
  { word: "bicycle", translation: "велосипед", category: "Транспорт" },
  { word: "motorcycle", translation: "мотоцикл", category: "Транспорт" },
  { word: "taxi", translation: "такси", category: "Транспорт" },
  { word: "subway", translation: "метро", category: "Транспорт" },
  { word: "truck", translation: "грузовик", category: "Транспорт" },
  { word: "helicopter", translation: "вертолёт", category: "Транспорт" },
  { word: "road", translation: "дорога", category: "Транспорт" },
  { word: "street", translation: "улица", category: "Транспорт" },
  { word: "bridge", translation: "мост", category: "Транспорт" },
  // Город и место
  { word: "city", translation: "город", category: "Город" },
  { word: "town", translation: "городок", category: "Город" },
  { word: "village", translation: "деревня", category: "Город" },
  { word: "country", translation: "страна", category: "Город" },
  { word: "school", translation: "школа", category: "Город" },
  { word: "university", translation: "университет", category: "Город" },
  { word: "hospital", translation: "больница", category: "Город" },
  { word: "shop", translation: "магазин", category: "Город" },
  { word: "market", translation: "рынок", category: "Город" },
  { word: "bank", translation: "банк", category: "Город" },
  { word: "hotel", translation: "отель", category: "Город" },
  { word: "restaurant", translation: "ресторан", category: "Город" },
  { word: "cafe", translation: "кафе", category: "Город" },
  { word: "park", translation: "парк", category: "Город" },
  { word: "church", translation: "церковь", category: "Город" },
  { word: "museum", translation: "музей", category: "Город" },
  { word: "library", translation: "библиотека", category: "Город" },
  { word: "airport", translation: "аэропорт", category: "Город" },
  { word: "station", translation: "вокзал", category: "Город" },
  { word: "office", translation: "офис", category: "Город" },
  { word: "factory", translation: "завод", category: "Город" },
  { word: "farm", translation: "ферма", category: "Город" },
  // Время
  { word: "time", translation: "время", category: "Время" },
  { word: "day", translation: "день", category: "Время" },
  { word: "night", translation: "ночь", category: "Время" },
  { word: "morning", translation: "утро", category: "Время" },
  { word: "afternoon", translation: "день (послеобед.)", category: "Время" },
  { word: "evening", translation: "вечер", category: "Время" },
  { word: "week", translation: "неделя", category: "Время" },
  { word: "month", translation: "месяц", category: "Время" },
  { word: "year", translation: "год", category: "Время" },
  { word: "hour", translation: "час", category: "Время" },
  { word: "minute", translation: "минута", category: "Время" },
  { word: "second", translation: "секунда", category: "Время" },
  { word: "today", translation: "сегодня", category: "Время" },
  { word: "yesterday", translation: "вчера", category: "Время" },
  { word: "tomorrow", translation: "завтра", category: "Время" },
  { word: "Monday", translation: "понедельник", category: "Время" },
  { word: "Tuesday", translation: "вторник", category: "Время" },
  { word: "Wednesday", translation: "среда", category: "Время" },
  { word: "Thursday", translation: "четверг", category: "Время" },
  { word: "Friday", translation: "пятница", category: "Время" },
  { word: "Saturday", translation: "суббота", category: "Время" },
  { word: "Sunday", translation: "воскресенье", category: "Время" },
  { word: "January", translation: "январь", category: "Время" },
  { word: "February", translation: "февраль", category: "Время" },
  { word: "March", translation: "март", category: "Время" },
  { word: "April", translation: "апрель", category: "Время" },
  { word: "May", translation: "май", category: "Время" },
  { word: "June", translation: "июнь", category: "Время" },
  { word: "July", translation: "июль", category: "Время" },
  { word: "August", translation: "август", category: "Время" },
  { word: "September", translation: "сентябрь", category: "Время" },
  { word: "October", translation: "октябрь", category: "Время" },
  { word: "November", translation: "ноябрь", category: "Время" },
  { word: "December", translation: "декабрь", category: "Время" },
  // Глаголы
  { word: "be", translation: "быть", category: "Глаголы" },
  { word: "have", translation: "иметь", category: "Глаголы" },
  { word: "do", translation: "делать", category: "Глаголы" },
  { word: "go", translation: "идти, ехать", category: "Глаголы" },
  { word: "come", translation: "приходить", category: "Глаголы" },
  { word: "get", translation: "получать", category: "Глаголы" },
  { word: "make", translation: "делать, создавать", category: "Глаголы" },
  { word: "know", translation: "знать", category: "Глаголы" },
  { word: "think", translation: "думать", category: "Глаголы" },
  { word: "see", translation: "видеть", category: "Глаголы" },
  { word: "look", translation: "смотреть", category: "Глаголы" },
  { word: "want", translation: "хотеть", category: "Глаголы" },
  { word: "give", translation: "давать", category: "Глаголы" },
  { word: "use", translation: "использовать", category: "Глаголы" },
  { word: "find", translation: "находить", category: "Глаголы" },
  { word: "tell", translation: "говорить, сказать", category: "Глаголы" },
  { word: "ask", translation: "спрашивать", category: "Глаголы" },
  { word: "work", translation: "работать", category: "Глаголы" },
  { word: "call", translation: "звонить, называть", category: "Глаголы" },
  { word: "try", translation: "пытаться", category: "Глаголы" },
  { word: "feel", translation: "чувствовать", category: "Глаголы" },
  { word: "leave", translation: "уходить, оставлять", category: "Глаголы" },
  { word: "put", translation: "класть", category: "Глаголы" },
  { word: "keep", translation: "хранить, держать", category: "Глаголы" },
  { word: "let", translation: "позволять", category: "Глаголы" },
  { word: "begin", translation: "начинать", category: "Глаголы" },
  { word: "show", translation: "показывать", category: "Глаголы" },
  { word: "hear", translation: "слышать", category: "Глаголы" },
  { word: "play", translation: "играть", category: "Глаголы" },
  { word: "run", translation: "бежать", category: "Глаголы" },
  { word: "move", translation: "двигаться", category: "Глаголы" },
  { word: "live", translation: "жить", category: "Глаголы" },
  { word: "believe", translation: "верить", category: "Глаголы" },
  { word: "hold", translation: "держать", category: "Глаголы" },
  { word: "bring", translation: "приносить", category: "Глаголы" },
  { word: "happen", translation: "случаться", category: "Глаголы" },
  { word: "write", translation: "писать", category: "Глаголы" },
  { word: "read", translation: "читать", category: "Глаголы" },
  { word: "spend", translation: "тратить (время/деньги)", category: "Глаголы" },
  { word: "stand", translation: "стоять", category: "Глаголы" },
  { word: "lose", translation: "терять", category: "Глаголы" },
  { word: "pay", translation: "платить", category: "Глаголы" },
  { word: "meet", translation: "встречать", category: "Глаголы" },
  { word: "include", translation: "включать", category: "Глаголы" },
  { word: "continue", translation: "продолжать", category: "Глаголы" },
  { word: "set", translation: "устанавливать", category: "Глаголы" },
  { word: "learn", translation: "учиться", category: "Глаголы" },
  { word: "change", translation: "менять", category: "Глаголы" },
  { word: "lead", translation: "вести", category: "Глаголы" },
  { word: "understand", translation: "понимать", category: "Глаголы" },
  { word: "watch", translation: "смотреть (телевизор)", category: "Глаголы" },
  { word: "follow", translation: "следовать", category: "Глаголы" },
  { word: "stop", translation: "останавливаться", category: "Глаголы" },
  { word: "create", translation: "создавать", category: "Глаголы" },
  { word: "speak", translation: "говорить", category: "Глаголы" },
  { word: "eat", translation: "есть", category: "Глаголы" },
  { word: "drink", translation: "пить", category: "Глаголы" },
  { word: "sleep", translation: "спать", category: "Глаголы" },
  { word: "sit", translation: "сидеть", category: "Глаголы" },
  { word: "walk", translation: "ходить пешком", category: "Глаголы" },
  { word: "open", translation: "открывать", category: "Глаголы" },
  { word: "close", translation: "закрывать", category: "Глаголы" },
  { word: "help", translation: "помогать", category: "Глаголы" },
  { word: "love", translation: "любить", category: "Глаголы" },
  { word: "like", translation: "нравиться", category: "Глаголы" },
  { word: "hate", translation: "ненавидеть", category: "Глаголы" },
  { word: "need", translation: "нуждаться", category: "Глаголы" },
  { word: "wait", translation: "ждать", category: "Глаголы" },
  { word: "send", translation: "отправлять", category: "Глаголы" },
  { word: "buy", translation: "покупать", category: "Глаголы" },
  { word: "sell", translation: "продавать", category: "Глаголы" },
  { word: "cook", translation: "готовить", category: "Глаголы" },
  { word: "clean", translation: "убирать", category: "Глаголы" },
  { word: "wash", translation: "мыть", category: "Глаголы" },
  { word: "drive", translation: "водить (машину)", category: "Глаголы" },
  { word: "fly", translation: "летать", category: "Глаголы" },
  { word: "swim", translation: "плавать", category: "Глаголы" },
  { word: "dance", translation: "танцевать", category: "Глаголы" },
  { word: "sing", translation: "петь", category: "Глаголы" },
  { word: "draw", translation: "рисовать", category: "Глаголы" },
  { word: "paint", translation: "красить, рисовать", category: "Глаголы" },
  { word: "laugh", translation: "смеяться", category: "Глаголы" },
  { word: "cry", translation: "плакать", category: "Глаголы" },
  { word: "smile", translation: "улыбаться", category: "Глаголы" },
  { word: "remember", translation: "помнить", category: "Глаголы" },
  { word: "forget", translation: "забывать", category: "Глаголы" },
  { word: "choose", translation: "выбирать", category: "Глаголы" },
  { word: "win", translation: "побеждать", category: "Глаголы" },
  { word: "break", translation: "ломать", category: "Глаголы" },
  { word: "build", translation: "строить", category: "Глаголы" },
  { word: "grow", translation: "расти", category: "Глаголы" },
  { word: "cut", translation: "резать", category: "Глаголы" },
  { word: "carry", translation: "нести", category: "Глаголы" },
  { word: "drop", translation: "ронять", category: "Глаголы" },
  { word: "catch", translation: "ловить", category: "Глаголы" },
  { word: "throw", translation: "бросать", category: "Глаголы" },
  { word: "kick", translation: "пинать", category: "Глаголы" },
  { word: "hit", translation: "ударять", category: "Глаголы" },
  { word: "push", translation: "толкать", category: "Глаголы" },
  { word: "pull", translation: "тянуть", category: "Глаголы" },
  { word: "type", translation: "печатать", category: "Глаголы" },
  { word: "save", translation: "сохранять, спасать", category: "Глаголы" },
  { word: "share", translation: "делиться", category: "Глаголы" },
  { word: "visit", translation: "посещать", category: "Глаголы" },
  { word: "travel", translation: "путешествовать", category: "Глаголы" },
  { word: "study", translation: "учиться, изучать", category: "Глаголы" },
  { word: "teach", translation: "учить (других)", category: "Глаголы" },
  { word: "explain", translation: "объяснять", category: "Глаголы" },
  { word: "answer", translation: "отвечать", category: "Глаголы" },
  { word: "check", translation: "проверять", category: "Глаголы" },
  // Прилагательные
  { word: "good", translation: "хороший", category: "Прилагательные" },
  { word: "bad", translation: "плохой", category: "Прилагательные" },
  { word: "big", translation: "большой", category: "Прилагательные" },
  { word: "small", translation: "маленький", category: "Прилагательные" },
  { word: "long", translation: "длинный", category: "Прилагательные" },
  { word: "short", translation: "короткий, низкий", category: "Прилагательные" },
  { word: "tall", translation: "высокий", category: "Прилагательные" },
  { word: "wide", translation: "широкий", category: "Прилагательные" },
  { word: "narrow", translation: "узкий", category: "Прилагательные" },
  { word: "heavy", translation: "тяжёлый", category: "Прилагательные" },
  { word: "light", translation: "лёгкий, светлый", category: "Прилагательные" },
  { word: "hot", translation: "горячий", category: "Прилагательные" },
  { word: "cold", translation: "холодный", category: "Прилагательные" },
  { word: "warm", translation: "тёплый", category: "Прилагательные" },
  { word: "cool", translation: "прохладный", category: "Прилагательные" },
  { word: "new", translation: "новый", category: "Прилагательные" },
  { word: "old", translation: "старый", category: "Прилагательные" },
  { word: "young", translation: "молодой", category: "Прилагательные" },
  { word: "fast", translation: "быстрый", category: "Прилагательные" },
  { word: "slow", translation: "медленный", category: "Прилагательные" },
  { word: "easy", translation: "лёгкий, простой", category: "Прилагательные" },
  { word: "hard", translation: "твёрдый, сложный", category: "Прилагательные" },
  { word: "strong", translation: "сильный", category: "Прилагательные" },
  { word: "weak", translation: "слабый", category: "Прилагательные" },
  { word: "happy", translation: "счастливый", category: "Прилагательные" },
  { word: "sad", translation: "грустный", category: "Прилагательные" },
  { word: "angry", translation: "злой", category: "Прилагательные" },
  { word: "tired", translation: "усталый", category: "Прилагательные" },
  { word: "hungry", translation: "голодный", category: "Прилагательные" },
  { word: "thirsty", translation: "жаждущий", category: "Прилагательные" },
  { word: "sick", translation: "больной", category: "Прилагательные" },
  { word: "healthy", translation: "здоровый", category: "Прилагательные" },
  { word: "beautiful", translation: "красивый", category: "Прилагательные" },
  { word: "ugly", translation: "некрасивый", category: "Прилагательные" },
  { word: "clean", translation: "чистый", category: "Прилагательные" },
  { word: "dirty", translation: "грязный", category: "Прилагательные" },
  { word: "rich", translation: "богатый", category: "Прилагательные" },
  { word: "poor", translation: "бедный", category: "Прилагательные" },
  { word: "right", translation: "правильный, правый", category: "Прилагательные" },
  { word: "wrong", translation: "неправильный", category: "Прилагательные" },
  { word: "important", translation: "важный", category: "Прилагательные" },
  { word: "interesting", translation: "интересный", category: "Прилагательные" },
  { word: "boring", translation: "скучный", category: "Прилагательные" },
  { word: "funny", translation: "смешной", category: "Прилагательные" },
  { word: "serious", translation: "серьёзный", category: "Прилагательные" },
  { word: "kind", translation: "добрый", category: "Прилагательные" },
  { word: "friendly", translation: "дружелюбный", category: "Прилагательные" },
  { word: "quiet", translation: "тихий", category: "Прилагательные" },
  { word: "loud", translation: "громкий", category: "Прилагательные" },
  { word: "free", translation: "свободный, бесплатный", category: "Прилагательные" },
  // Наречия
  { word: "now", translation: "сейчас", category: "Наречия" },
  { word: "then", translation: "тогда", category: "Наречия" },
  { word: "here", translation: "здесь", category: "Наречия" },
  { word: "there", translation: "там", category: "Наречия" },
  { word: "very", translation: "очень", category: "Наречия" },
  { word: "well", translation: "хорошо", category: "Наречия" },
  { word: "just", translation: "только что, просто", category: "Наречия" },
  { word: "also", translation: "также", category: "Наречия" },
  { word: "still", translation: "всё ещё", category: "Наречия" },
  { word: "already", translation: "уже", category: "Наречия" },
  { word: "always", translation: "всегда", category: "Наречия" },
  { word: "never", translation: "никогда", category: "Наречия" },
  { word: "often", translation: "часто", category: "Наречия" },
  { word: "sometimes", translation: "иногда", category: "Наречия" },
  { word: "usually", translation: "обычно", category: "Наречия" },
  { word: "soon", translation: "скоро", category: "Наречия" },
  { word: "late", translation: "поздно", category: "Наречия" },
  { word: "early", translation: "рано", category: "Наречия" },
  { word: "fast", translation: "быстро", category: "Наречия" },
  { word: "slowly", translation: "медленно", category: "Наречия" },
  { word: "together", translation: "вместе", category: "Наречия" },
  { word: "alone", translation: "один, одиноко", category: "Наречия" },
  { word: "almost", translation: "почти", category: "Наречия" },
  { word: "really", translation: "действительно", category: "Наречия" },
  { word: "too", translation: "тоже, слишком", category: "Наречия" },
  // Предлоги
  { word: "in", translation: "в (внутри)", category: "Предлоги" },
  { word: "on", translation: "на", category: "Предлоги" },
  { word: "at", translation: "у, в (место/время)", category: "Предлоги" },
  { word: "to", translation: "к, в (направление)", category: "Предлоги" },
  { word: "from", translation: "от, из", category: "Предлоги" },
  { word: "with", translation: "с", category: "Предлоги" },
  { word: "without", translation: "без", category: "Предлоги" },
  { word: "for", translation: "для, за", category: "Предлоги" },
  { word: "of", translation: "из, от (принадлежность)", category: "Предлоги" },
  { word: "about", translation: "о, около", category: "Предлоги" },
  { word: "under", translation: "под", category: "Предлоги" },
  { word: "over", translation: "над, через", category: "Предлоги" },
  { word: "between", translation: "между", category: "Предлоги" },
  { word: "before", translation: "до, перед", category: "Предлоги" },
  { word: "after", translation: "после", category: "Предлоги" },
  { word: "next to", translation: "рядом с", category: "Предлоги" },
  { word: "behind", translation: "за, позади", category: "Предлоги" },
  { word: "through", translation: "через, сквозь", category: "Предлоги" },
  { word: "during", translation: "во время", category: "Предлоги" },
  { word: "near", translation: "около, рядом", category: "Предлоги" },
  // Союзы и частицы
  { word: "and", translation: "и", category: "Союзы" },
  { word: "or", translation: "или", category: "Союзы" },
  { word: "but", translation: "но", category: "Союзы" },
  { word: "because", translation: "потому что", category: "Союзы" },
  { word: "if", translation: "если", category: "Союзы" },
  { word: "when", translation: "когда", category: "Союзы" },
  { word: "where", translation: "где", category: "Союзы" },
  { word: "while", translation: "пока, в то время как", category: "Союзы" },
  { word: "although", translation: "хотя", category: "Союзы" },
  { word: "so", translation: "поэтому, так", category: "Союзы" },
  { word: "not", translation: "не", category: "Союзы" },
  { word: "yes", translation: "да", category: "Союзы" },
  { word: "no", translation: "нет", category: "Союзы" },
  // Числа
  { word: "one", translation: "один", category: "Числа" },
  { word: "two", translation: "два", category: "Числа" },
  { word: "three", translation: "три", category: "Числа" },
  { word: "four", translation: "четыре", category: "Числа" },
  { word: "five", translation: "пять", category: "Числа" },
  { word: "six", translation: "шесть", category: "Числа" },
  { word: "seven", translation: "семь", category: "Числа" },
  { word: "eight", translation: "восемь", category: "Числа" },
  { word: "nine", translation: "девять", category: "Числа" },
  { word: "ten", translation: "десять", category: "Числа" },
  { word: "eleven", translation: "одиннадцать", category: "Числа" },
  { word: "twelve", translation: "двенадцать", category: "Числа" },
  { word: "twenty", translation: "двадцать", category: "Числа" },
  { word: "thirty", translation: "тридцать", category: "Числа" },
  { word: "forty", translation: "сорок", category: "Числа" },
  { word: "fifty", translation: "пятьдесят", category: "Числа" },
  { word: "hundred", translation: "сто", category: "Числа" },
  { word: "thousand", translation: "тысяча", category: "Числа" },
  { word: "first", translation: "первый", category: "Числа" },
  { word: "second", translation: "второй", category: "Числа" },
  { word: "third", translation: "третий", category: "Числа" },
  // Тело
  { word: "body", translation: "тело", category: "Тело" },
  { word: "head", translation: "голова", category: "Тело" },
  { word: "face", translation: "лицо", category: "Тело" },
  { word: "eye", translation: "глаз", category: "Тело" },
  { word: "ear", translation: "ухо", category: "Тело" },
  { word: "nose", translation: "нос", category: "Тело" },
  { word: "mouth", translation: "рот", category: "Тело" },
  { word: "tooth", translation: "зуб", category: "Тело" },
  { word: "hair", translation: "волосы", category: "Тело" },
  { word: "neck", translation: "шея", category: "Тело" },
  { word: "shoulder", translation: "плечо", category: "Тело" },
  { word: "arm", translation: "рука (от плеча)", category: "Тело" },
  { word: "hand", translation: "рука (кисть)", category: "Тело" },
  { word: "finger", translation: "палец", category: "Тело" },
  { word: "chest", translation: "грудь", category: "Тело" },
  { word: "back", translation: "спина", category: "Тело" },
  { word: "leg", translation: "нога", category: "Тело" },
  { word: "foot", translation: "стопа", category: "Тело" },
  { word: "heart", translation: "сердце", category: "Тело" },
  { word: "skin", translation: "кожа", category: "Тело" },
  // Цвета
  { word: "red", translation: "красный", category: "Цвета" },
  { word: "blue", translation: "синий, голубой", category: "Цвета" },
  { word: "green", translation: "зелёный", category: "Цвета" },
  { word: "yellow", translation: "жёлтый", category: "Цвета" },
  { word: "orange", translation: "оранжевый", category: "Цвета" },
  { word: "purple", translation: "фиолетовый", category: "Цвета" },
  { word: "pink", translation: "розовый", category: "Цвета" },
  { word: "black", translation: "чёрный", category: "Цвета" },
  { word: "white", translation: "белый", category: "Цвета" },
  { word: "grey", translation: "серый", category: "Цвета" },
  { word: "brown", translation: "коричневый", category: "Цвета" },
  { word: "gold", translation: "золотой", category: "Цвета" },
  { word: "silver", translation: "серебряный", category: "Цвета" },
  // Школа и работа
  { word: "book", translation: "книга", category: "Учёба" },
  { word: "pen", translation: "ручка", category: "Учёба" },
  { word: "pencil", translation: "карандаш", category: "Учёба" },
  { word: "paper", translation: "бумага", category: "Учёба" },
  { word: "notebook", translation: "тетрадь", category: "Учёба" },
  { word: "lesson", translation: "урок", category: "Учёба" },
  { word: "homework", translation: "домашнее задание", category: "Учёба" },
  { word: "test", translation: "тест", category: "Учёба" },
  { word: "exam", translation: "экзамен", category: "Учёба" },
  { word: "answer", translation: "ответ", category: "Учёба" },
  { word: "question", translation: "вопрос", category: "Учёба" },
  { word: "word", translation: "слово", category: "Учёба" },
  { word: "sentence", translation: "предложение", category: "Учёба" },
  { word: "language", translation: "язык", category: "Учёба" },
  { word: "grammar", translation: "грамматика", category: "Учёба" },
  { word: "dictionary", translation: "словарь", category: "Учёба" },
  { word: "money", translation: "деньги", category: "Учёба" },
  { word: "job", translation: "работа, должность", category: "Учёба" },
  { word: "salary", translation: "зарплата", category: "Учёба" },
  { word: "meeting", translation: "встреча, собрание", category: "Учёба" },
  // Разное
  { word: "name", translation: "имя", category: "Разное" },
  { word: "age", translation: "возраст", category: "Разное" },
  { word: "address", translation: "адрес", category: "Разное" },
  { word: "number", translation: "номер, число", category: "Разное" },
  { word: "letter", translation: "письмо, буква", category: "Разное" },
  { word: "message", translation: "сообщение", category: "Разное" },
  { word: "photo", translation: "фотография", category: "Разное" },
  { word: "video", translation: "видео", category: "Разное" },
  { word: "music", translation: "музыка", category: "Разное" },
  { word: "song", translation: "песня", category: "Разное" },
  { word: "game", translation: "игра", category: "Разное" },
  { word: "sport", translation: "спорт", category: "Разное" },
  { word: "team", translation: "команда", category: "Разное" },
  { word: "prize", translation: "приз", category: "Разное" },
  { word: "news", translation: "новости", category: "Разное" },
  { word: "idea", translation: "идея", category: "Разное" },
  { word: "problem", translation: "проблема", category: "Разное" },
  { word: "plan", translation: "план", category: "Разное" },
  { word: "dream", translation: "мечта, сон", category: "Разное" },
  { word: "life", translation: "жизнь", category: "Разное" },
  { word: "world", translation: "мир", category: "Разное" },
  { word: "people", translation: "люди", category: "Разное" },
  { word: "place", translation: "место", category: "Разное" },
  { word: "thing", translation: "вещь, предмет", category: "Разное" },
  { word: "way", translation: "путь, способ", category: "Разное" },
  { word: "part", translation: "часть", category: "Разное" },
  { word: "side", translation: "сторона", category: "Разное" },
  { word: "end", translation: "конец", category: "Разное" },
  { word: "start", translation: "начало", category: "Разное" },
  { word: "help", translation: "помощь", category: "Разное" },
  { word: "health", translation: "здоровье", category: "Разное" },
  { word: "love", translation: "любовь", category: "Разное" },
  { word: "peace", translation: "мир, покой", category: "Разное" },
  { word: "war", translation: "война", category: "Разное" },
  { word: "power", translation: "сила, власть", category: "Разное" },
  { word: "truth", translation: "правда", category: "Разное" },
  { word: "story", translation: "история, рассказ", category: "Разное" },
];

const categories = ["Все", ...Array.from(new Set(words.map((w) => w.category)))];

export function WordList() {
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState("Все");

  const filtered = words.filter((w) => {
    const matchCat = activeCategory === "Все" || w.category === activeCategory;
    const matchSearch =
      w.word.toLowerCase().includes(search.toLowerCase()) ||
      w.translation.toLowerCase().includes(search.toLowerCase());
    return matchCat && matchSearch;
  });

  return (
    <section id="wordlist" className="py-16 lg:py-24 bg-muted/20">
      <div className="container mx-auto px-4 lg:px-8">
        <div className="mb-10">
          <h2 className="font-serif text-4xl lg:text-5xl font-light mb-4">1000 английских слов</h2>
          <p className="text-muted-foreground text-lg mb-6">
            Полный базовый словарь с переводом — ищите по слову или выбирайте категорию
          </p>

          <div className="flex flex-col gap-4">
            <div className="relative max-w-md">
              <Icon name="Search" size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="Поиск слова или перевода..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-9"
              />
            </div>

            <div className="flex flex-wrap gap-2">
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={`text-xs px-3 py-1.5 rounded-full border transition-colors ${
                    activeCategory === cat
                      ? "bg-foreground text-background border-foreground"
                      : "bg-background text-muted-foreground border-border hover:border-foreground"
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="mb-4 text-sm text-muted-foreground">
          Показано слов: <strong>{filtered.length}</strong> из {words.length}
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-3">
          {filtered.map((w, i) => (
            <div
              key={i}
              className="bg-card border rounded-lg p-3 hover:shadow-sm transition-shadow"
            >
              <p className="font-medium text-sm">{w.word}</p>
              <p className="text-xs text-muted-foreground mt-0.5">{w.translation}</p>
              <span className="inline-block mt-2 text-xs bg-muted px-1.5 py-0.5 rounded text-muted-foreground">
                {w.category}
              </span>
            </div>
          ))}
        </div>

        {filtered.length === 0 && (
          <div className="text-center py-16 text-muted-foreground">
            <Icon name="Search" size={40} className="mx-auto mb-4 opacity-30" />
            <p>Слово не найдено — попробуйте другой запрос</p>
          </div>
        )}
      </div>
    </section>
  );
}
